import Head from "next/head";
import OurTeam from "../../components/About/OurTeam";
import styles from "../../styles/About/About.module.css";

export default function Home() {
    return (
        <div className="flex flex-col items-center justify-start w-11/12 md:w-10/12 lg:9/12 xl:w-8/12">
            <Head>
                <title>Fortney Fine Properties - About</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <p
                className={`w-10/12 mt-8 text-3xl font-bold text-center text-black md:mt-16 md:text-4xl md:w-2/3 ${styles["AboutMainTitle"]} riseAndFade`}
            >
                Fortney Fine Properties is a leading independent brokerage firm
                serving Northern Virginia, Maryland, and Washington, D.C.
            </p>

            <OurTeam />
            {/* <OurTeam />
            <OurStory /> */}
        </div>
    );
}
