import Head from "next/head";
import FeaturedListings from "../components/Home/FeaturedListings";
import Hero from "../components/Home/Hero";
import Search from "../components/Home/Search";
import styles from "../styles/Home/Home.module.css";

import Link from "next/link";

export default function Home() {
    return (
        <div className="flex flex-col items-center justify-start w-11/12 md:w-10/12 lg:9/12 xl:w-8/12 riseAndFade">
            <Head>
                <title>Fortney Fine Properties - Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            <Hero />
            <FeaturedListings />
            <Search />

            <div className="flex flex-col items-center justify-center my-36">
                <h3 className="text-4xl font-bold text-center text-black">
                    Looking to list your property?
                </h3>
                <p className="mt-6 text-lg font-normal text-center">
                    Learn more about how we can help you prepare your property
                    for sale and get you the best price, with less stress.
                </p>
                <Link href="/sellers">
                    <a className="py-4 mx-auto mt-6 text-base font-bold text-white transition-colors rounded-lg px-7 bg-ffp-blue hover:bg-ffp-green">
                        Learn More
                    </a>
                </Link>
            </div>
        </div>
    );
}
